donor + donation
bnowacki/humanitarian-aid-coordination-system pull request #2
Opened 2024-12-17 12:15 UTC by TymPiwowar

basic UI for donations

2024-12-17 12:15 UTC, TymPiwowar commented
please merge!

2024-12-17 12:35 UTC, bnowacki requested changes

2024-12-17 12:35 UTC, bnowacki commented on package.json
> +    "@emotion/react": "^11.14.0",
```suggestion
    "@chakra-ui/next-js": "^2.4.2",
    "@chakra-ui/react": "^3.2.3",
    "@emotion/react": "^11.14.0",
```

wrong folder, uninstall these libraries from here

2024-12-17 12:35 UTC, bnowacki commented on web/package.json
> +    "react-router-dom": "^7.0.2",
```suggestion
```

we are using nextjs, in nextjs `react-router-dom` is not needed - the paths are defined based on folder structure

2024-12-17 12:35 UTC, bnowacki commented on web/src/app/[locale]/(app)/donations/event/page.tsx
> +import { useRouter, useSearchParams } from 'next/navigation'
```suggestion
import { useSearchParams  } from 'next/navigation'
import { useRouter } from '@/i18n/navigation'
```

use internationalized routing, in this way there are less redirects

2024-12-17 12:35 UTC, bnowacki commented on web/src/app/[locale]/(app)/donations/event/page.tsx
> +import { useRouter, useSearchParams } from 'next/navigation'
this comment applies to all files

2024-12-17 12:35 UTC, bnowacki commented on web/src/app/[locale]/(app)/donations/form.tsx
is this file needed?

2024-12-17 12:35 UTC, bnowacki commented on web/tsconfig.json
> +    "src/app/[locale]/(app)/donations/donate/event.tsx"
```suggestion
```
what why

2024-12-17 12:35 UTC, bnowacki commented on web/src/app/[locale]/(app)/donations/event/page.tsx
> +        {type ? `Donation Campaigns for ${type}` : 'Donation Campaigns'}
Missing translations, use `useTranslations()` from `next-intl` there are examples how it works in other files in this repo. This comment applies to all your files

2024-12-17 12:35 UTC, bnowacki commented on web/package.json
> +    "react-router-dom": "^7.0.2",
uninstall it

2025-01-03 18:28 UTC, TymPiwowar commented
Hello, I think it is ready to merge!

2025-01-03 19:23 UTC, bnowacki approved these changes

2025-01-03 19:36 UTC, merged